#!/usr/bin/env ruby -wKU
# encoding: UTF-8

usage = <<TXT
Usage: iq_gem.rb YOUR_GEM.gemspec SSH_USER REMOTE_GEM_REPO
TXT

if ARGV.size < 3
  puts usage
  exit 1
end

gemspec = ARGV[0]
ssh_user = ARGV[1]
gem_host = "gems.innoq.com"
gem_tree = "/var/www/gems"
gem_repo = "#{gem_tree}/#{ARGV[2]}/gems"

build = `gem build #{gemspec}`
build.match(/File:\s(.*)/)

gem_file = $1.strip
puts gem_file

system "scp #{gem_file} #{ssh_user}@gems.innoq.com:#{gem_repo}/"
system "ssh #{ssh_user}@gems.innoq.com \"bash -l -c 'gem generate_index --directory #{gem_tree}/*'\""
